# valid log levels: debug, info (default), warn, error
logLevel: debug

models:

  "qwen3-coder-30B":
    cmd: |
      /home/davpace/llama.cpp/build/bin/llama-server 
      --model /home/davpace/Models/Qwen3-Coder-30B-A3B-Instruct-UD-Q4_K_XL.gguf
      --jinja 
      --threads 20 
      --ctx-size 64000
      --temp 0.7 --min-p 0.0 --top-p 0.80 --top-k 20 --repeat-penalty 1.05 
      --cpu-moe
      --port ${PORT}  
      -ngl auto
      --fit on
    ttl: 900

  "gpt-oss":
    cmd: |
      /home/davpace/llama.cpp/build/bin/llama-server 
      --model /home/davpace/Models/gpt-oss-20b-F16.gguf
      --jinja -ngl auto --threads 20 --ctx-size 128000 
      --temp 0.6 --top-p 1.0 --top-k 0 
      -ot ".ffn_(up|down)_exps.=CPU"
      --port ${PORT} 
      --fit on
      --chat-template-kwargs '{"reasoning_effort": "high"}'
    ttl: 900

  "glm-4.7-flash":
    cmd: |
      /home/davpace/llama.cpp/build/bin/llama-server
      --model /home/davpace/Models/GLM-4.7-Flash-UD-Q4_K_XL.gguf
      --jinja
      --threads 20
      --ctx-size 128000
      --temp 0.7
      --top-p 1.0
      --min-p 0.01
      --port ${PORT}
      --fit on
      --cpu-moe
      -ngl auto
      # --chat-template-kwargs '{"enable_thinking": false}'
    ttl: 900

