name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: Gemma3-12b
    provider: openai
    apiBase: http://localhost:8080/v1
    model: gemma3-12b
    capabilitites:
      - image_input
    chatOptions: 
      baseSystemMessage: ""
    roles:
      - chat
      - edit
      - apply

  - name: Qwen3-30B
    provider: openai
    apiBase: http://localhost:8080/v1
    model: qwen3-30B
    capabilitites:
      - tool_use
    chatOptions: 
      baseSystemMessage: ""
    roles:
      - chat
      - edit
      - apply
      
  - name: Qwen2.5-coder-7b
    provider: openai
    apiBase: http://localhost:8080/v1
    model: qwen2.5-coder-7b
    roles:
      - autocomplete
  
  - name: Magistral
    provider: openai
    apiBase: http://localhost:8080/v1
    model: magistral
    chatOptions: 
      baseSystemMessage: ""
    roles:
      - chat
      - edit
      - apply

context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
