name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: gpt-oss
    provider: openai
    apiBase: http://localhost:8080/v1/
    model: gpt-oss
    defaultCompletionOptions:
      contextLength: 80000
      maxTokens: 16384
    capabilities:
      - tool_use
    chatOptions:
      baseSystemMessage: "Reasoning: high"
    roles:
      - chat
      - edit
      - apply
      - autocomplete
  - name: Qwen3-30B-Coder
    provider: openai
    apiBase: http://localhost:8080/v1/
    model: qwen3-coder-30B
    defaultCompletionOptions:
      contextLength: 80000
      maxTokens: 16384
    capabilities:
      - tool_use
    roles:
      - chat
      - edit
      - apply
      - autocomplete
  - name: GLM-4.7-FLash
    provider: openai
    apiBase: http://localhost:8080/v1/
    model: glm-4.7-flash
    defaultCompletionOptions:
      contextLength: 80000
      maxTokens: 16384
    capabilities:
      - tool_use
    roles:
      - chat
      - edit
      - apply
      - autocomplete
  - name: Qwen2.5-coder-3b
    provider: openai
    apiBase: http://localhost:8080/v1
    model: qwen2.5-coder:3b
    roles:
      - autocomplete
  - name: Autodetect
    provider: ollama
    model: AUTODETECT
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
